baseurl      = "http://blog.cotero.org/"
languageCode = "en-us"
title        = "Berenice's Blog"
theme        = "angels-ladder"

[Params]
subtitle     = "Life, art and IT"
facebook     = "https://www.facebook.com/clamorisse"
twitter      = "https://twitter.com/clamorisse"
github       = "https://github.com/clamorisse"
showsRSS     = true
copyright    = "Written by Berenice Venegas 2016"
  
