machine:
  timezone:
    America/New_York
  services:
    - docker

dependencies:
  override:
    - docker info
    - docker build -t bvcotero/hugo .

test:
  post:
    - docker run -d -it  -p 1313:1313 -v $(pwd):/root/hugo bvcotero/hugo
  sleep 10
    - curl --retry 2 --retry-delay 5 -v http://localhost:1313
