baseurl      = "http://clamorisse-blog.s3-website-us-east-1.amazonaws.com/"
languageCode = "en-us"
title        = "Colette's garage"
theme        = "angels-ladder"

[Params]
subtitle     = "Because all interesting things start in the garage!"
facebook     = "https://www.facebook.com/clamorisse"
twitter      = "https://twitter.com/clamorisse"
github       = "https://github.com/clamorisse"
showsRSS     = true
copyright    = "Written by Berenice Venegas"
  
